apiVersion: v1
kind: Deployment
metadata:
  name: obj-det
  namespace: default
  labels:
    app: yolo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        image: rohanjamadagni/obj-det-fastapi:latest
        ports:
        - containerPort: 8000
          name: web-api
          protocol: TCP
