apiVersion: apps/v1
kind: Deployment
metadata:
  name: obj-det
  namespace: default
  labels:
    app: yolo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      volumes:
        - name: mongo-config
          configMap:
            name: mongo-conf
      containers:
      - name: yolo
        image: rohanjamadagni/obj-det-fastapi:latest
        ports:
        - containerPort: 8000
          name: web-api
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
            - name: mongo-config
              mountPath: /app/mongo-config
